name: continuous-deployment

on:
  push:
    branches:
      - master
    paths:
      - 'packages/docs/**'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      # Compare https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Compare `scripts.build` in
      # https://github.com/jrappen/recipes/blob/master/packages/docs/package.json
      - name: Build docs
        run: |
          cd packages/docs
          yarn build

      # Compare https://github.com/peaceiris/actions-gh-pages
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: 'deploy:'
